### ISSUE TITLE
Data formatting

### ISSUE THREAD

**Issue by andrew-hipp** [andrew-hipp/prairie-biomass-2018#2]
Please review how the data objects are built -- do they work for your analyses?

**Comment by lanescher** [comment]
It works, but I get a little confused with all the different objects. Could we just make one dataframe with all of the data for all the plots? I can make it, just wondering if it would be useful to you both. I know there's some data that wouldn't fit, but it could have most of it.

**Comment by lanescher** [comment]
Lane and Ashley decided that we should make a new dataframe with all the data. This has been delegated to Ashley.

**Comment by altuffin** [comment]
New dataframe made (all.prairie) using script "001.compileData.R"

**Comment by andrew-hipp** [comment]
This is complicated by the fact that many files are being read multiple times and several copies in the workspace. I'm closing this issue and reopening a new one regarding this issue.
