### ISSUE TITLE
OS Differences

### ISSUE THREAD

**Issue by altuffin** [andrew-hipp/prairie-biomass-2018#4]
When trying to run the script 00.readData.R, I noticed that the scirpt would not continue past line 19:

tr.prairie <- read.tree('../DATA/tree.pruned.tre')

I believe this is because of the differences in R between MacOS and Windows/Linux? For the line to complete on my Mac (from the working directory of "prairie-biomass-2018") it would read:

tr.prairie <- read.tree('DATA/tree.pruned.tre')

How do we resolve this issue?

**Comment by andrew-hipp** [comment]
This is probably not an OS issue... the same path would be used in Unix, and MacOS is POSIX-compliant. Perhaps you are running R not in the Workspace folder, but in the folder that contains WORKSPACE and DATA. Please check and let me know. Thanks!

**Comment by altuffin** [comment]
You are right! I misunderstood where the working directory was supposed to be set. All seems to be working now!
