### ISSUE TITLE
NDVI vs Biomass Sensitivity

### ISSUE THREAD

**Issue by altuffin** [andrew-hipp/prairie-biomass-2018#5]
Right now, our t.test that examines Block A to its replicates only looks at treatment plots, not monocultures. Do the monocultures also have replicates dispersed in the opposite superblock that we could incorporate into this test? We have NDVI and biomass from the monocultures as well as the treatments, would it be wise to use them?

**Comment by andrew-hipp** [comment]
They do. It makes sense to conduct the analysis (1) by monocultures, (2) by plug treatments, (3) by seed treatments, and (4) by all.
